version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: django_db
    restart: always
    environment:
      MYSQL_DATABASE: django_db
      MYSQL_USER: taishi
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - 3306

  gunicorn:
    container_name: django_app
    build:
      context: .
      dockerfile: ./learning_app/Dockerfile
      args:
        - ENV_FILE=${ENV_FILE}
    volumes:
      #- ./learning_app/:/usr/src/app/   これをやるとリモートで.env.devファイルがなくなる
      - gunicorn:/var/run/gunicorn
    ports:
      - 8000:8000

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./docker_nginx/Dockerfile
      args:
        - ENV_FILE=${ENV_FILE}
    ports:
      - 80:80
    volumes:
      #- ./learning_app/:/usr/src/app/
      - ./nginx:/etc/nginx
      - gunicorn:/var/run/gunicorn



volumes:
  gunicorn:
    driver: local

