# circleCIのバージョン指定
version: 2.1
jobs:
  build:
    working_directory: ~/learning_app_container
    machine:
      image: circleci/classic:edge
    steps:
# Djangoのテストを実行
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for launch db to migrate at Django
          command: sleep 10
      - run:
          name: check
          command: ls mysql
      - run:
          name: migrate
          #command: docker-compose ps && docker-compose logs -f 
          command: docker-compose ps && docker-compose run gunicorn python ./manage.py migrate
      - run:
          name: test
          command: docker-compose run gunicorn python ./manage.py test
      - run:
          name: docker-compose down
          command: docker-compose down
# EC2にSSH接続し、デプロイを実行
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
          fingerprints:
          - "f9:9f:6d:cc:bd:1f:2d:28:8b:be:15:bd:60:4d:5d:ff"
      - run: ssh -vvv ${USER_NAME}@${HOST_NAME} 'cd todoList && git pull && docker-compose run python ./manage.py migrate' && sshd_config

# テストが成功した場合のみ、deployを実行するようにします。
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # masterブランチがpushされた場合のみdeployするようにする。
          filters:
            branches:
              only: master