# circleCIのバージョン指定 
version: 2.1
jobs:
  build:
    working_directory: ~/learning_app_container
    machine:
      image: ubuntu-2004:202111-02
    steps:
# Djangoのテストを実行
      - checkout
      - run:
          name: make .env.dev
          command: echo ENV_FILE=${ENV_FILE} > .env
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: output
          command: docker-compose ps
      - run:
          name: sleep for launch db to migrate at Django
          command: sleep 15
      - run:
          name: migrate
          command: docker-compose run gunicorn python ./manage.py migrate && docker-compose ps
      - run:
          name: test
          command: docker-compose run gunicorn python ./manage.py test
      - run:
          name: docker-compose down
          command: docker-compose down
# EC2にSSH接続し、デプロイを実行
  deploy:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
          fingerprints:
          - "fb:2c:4b:39:fd:e5:22:82:99:f0:47:d8:01:4d:93:6b"
      - run: ssh -vvv ${USER_NAME}@${HOST_NAME} 'cd learning_app_docker && git pull && sudo docker-compose build  && sudo docker-compose up -d && sleep 15 && sudo docker-compose run gunicorn python ./manage.py migrate'

# テストが成功した場合のみ、deployを実行するようにします。
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # masterブランチがpushされた場合のみdeployするようにする。
          filters:
            branches:
              only: master