# circleCIのバージョン指定
version: 2.1
jobs:
  build:
    working_directory: ~/learning_app_container
    machine:
      image: circleci/classic:edge
    steps:
# Djangoのテストを実行
      - checkout
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for launch db to migrate at Django
          command: sleep 3
      - run:
          name: migrate
          #command: docker-compose ps && docker-compose logs -f
          command: docker-compose ps && docker-compose run gunicorn python ./manage.py migrate
      - run:
          name: test
          command: docker-compose run gunicorn python ./manage.py test
      - run:
          name: docker-compose down
          command: docker-compose down
# EC2にSSH接続し、デプロイを実行
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCIに登録した秘密鍵を呼び出す。
      - add_ssh_keys:
          fingerprints:
          - "5b:b8:2f:48:a5:e0:21:9a:87:33:66:a6:46:f0:1e:fa"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd todoList && git pull && docker-compose run python ./manage.py migrate'

# テストが成功した場合のみ、deployを実行するようにします。
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # masterブランチがpushされた場合のみdeployするようにする。
          filters:
            branches:
              only: master