# Generated by Django 2.2.24 on 2021-11-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_problem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='content',
            field=models.CharField(max_length=200, verbose_name='選択肢'),
        ),
    ]
