# Generated by Django 2.2.24 on 2021-11-16 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211109_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Problem'),
        ),
    ]
