# Generated by Django 2.2.24 on 2021-11-16 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211116_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Problem'),
        ),
    ]
