# Generated by Django 2.2.24 on 2021-11-17 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211117_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='explain',
            field=models.TextField(blank=True, max_length=400, verbose_name='分野に関する説明'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=50, verbose_name='分野'),
        ),
        migrations.CreateModel(
            name='SubField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='サブ分野')),
                ('explain', models.TextField(blank=True, max_length=400, verbose_name='分野に関する説明')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject')),
            ],
        ),
    ]
