# Generated by Django 2.2.24 on 2021-11-17 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211117_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubField',
            new_name='SubSubject',
        ),
    ]
