# Generated by Django 2.2.24 on 2021-11-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211117_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubSubject',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Title'),
        ),
    ]
