# Generated by Django 2.2.24 on 2021-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211117_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='explain',
            field=models.TextField(blank=True, max_length=400, verbose_name='タイトルに関する説明'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=50, verbose_name='タイトル'),
        ),
    ]
