# Generated by Django 2.2.24 on 2021-11-18 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211118_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Title'),
        ),
    ]
