# Generated by Django 2.2.24 on 2021-11-18 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211118_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='問題を作成したユーザ'),
        ),
    ]
