# Generated by Django 2.2.24 on 2021-11-19 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211119_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='solving_user',
            field=models.ManyToManyField(related_name='solving_problem', to=settings.AUTH_USER_MODEL, verbose_name='問題を解いたユーザ'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='making_problem', to=settings.AUTH_USER_MODEL, verbose_name='問題を作成したユーザ'),
        ),
    ]
