# Generated by Django 2.2.24 on 2021-12-10 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_schoolyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='school_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.SchoolYear'),
        ),
    ]
