# Generated by Django 2.2.24 on 2021-12-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211210_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation_problem',
            name='add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculation_problem',
            name='div',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculation_problem',
            name='mul',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calculation_problem',
            name='sub',
            field=models.BooleanField(default=False),
        ),
    ]
