# Generated by Django 2.2.24 on 2021-12-10 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211210_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation_problem',
            name='solving_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
